/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcGocamTable {
        "keyword": any;
    }
}
declare global {
    interface HTMLWcGocamTableElement extends Components.WcGocamTable, HTMLStencilElement {
    }
    var HTMLWcGocamTableElement: {
        prototype: HTMLWcGocamTableElement;
        new (): HTMLWcGocamTableElement;
    };
    interface HTMLElementTagNameMap {
        "wc-gocam-table": HTMLWcGocamTableElement;
    }
}
declare namespace LocalJSX {
    interface WcGocamTable {
        "keyword"?: any;
    }
    interface IntrinsicElements {
        "wc-gocam-table": WcGocamTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-gocam-table": LocalJSX.WcGocamTable & JSXBase.HTMLAttributes<HTMLWcGocamTableElement>;
        }
    }
}
