/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcGocPaginator {
        "itemCount": number;
        "pageNumber": number;
        "pageSize": number;
        "sizeOptions": number[];
        "title": string;
    }
    interface WcGocamTable {
        "keyword": any;
        "paginationClass": string;
    }
}
declare global {
    interface HTMLWcGocPaginatorElement extends Components.WcGocPaginator, HTMLStencilElement {
    }
    var HTMLWcGocPaginatorElement: {
        prototype: HTMLWcGocPaginatorElement;
        new (): HTMLWcGocPaginatorElement;
    };
    interface HTMLWcGocamTableElement extends Components.WcGocamTable, HTMLStencilElement {
    }
    var HTMLWcGocamTableElement: {
        prototype: HTMLWcGocamTableElement;
        new (): HTMLWcGocamTableElement;
    };
    interface HTMLElementTagNameMap {
        "wc-goc-paginator": HTMLWcGocPaginatorElement;
        "wc-gocam-table": HTMLWcGocamTableElement;
    }
}
declare namespace LocalJSX {
    interface WcGocPaginator {
        "itemCount"?: number;
        "onPageChanged"?: (event: CustomEvent<any>) => void;
        "onSizeChanged"?: (event: CustomEvent<any>) => void;
        "pageNumber"?: number;
        "pageSize"?: number;
        "sizeOptions"?: number[];
        "title"?: string;
    }
    interface WcGocamTable {
        "keyword"?: any;
        "paginationClass"?: string;
    }
    interface IntrinsicElements {
        "wc-goc-paginator": WcGocPaginator;
        "wc-gocam-table": WcGocamTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-goc-paginator": LocalJSX.WcGocPaginator & JSXBase.HTMLAttributes<HTMLWcGocPaginatorElement>;
            "wc-gocam-table": LocalJSX.WcGocamTable & JSXBase.HTMLAttributes<HTMLWcGocamTableElement>;
        }
    }
}
