/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcGocPaginator {
        "itemCount": number;
        "page": number;
        "pageSize": number;
        "sizeOptions": number[];
    }
}
declare global {
    interface HTMLWcGocPaginatorElement extends Components.WcGocPaginator, HTMLStencilElement {
    }
    var HTMLWcGocPaginatorElement: {
        prototype: HTMLWcGocPaginatorElement;
        new (): HTMLWcGocPaginatorElement;
    };
    interface HTMLElementTagNameMap {
        "wc-goc-paginator": HTMLWcGocPaginatorElement;
    }
}
declare namespace LocalJSX {
    interface WcGocPaginator {
        "itemCount"?: number;
        "onPageChanged"?: (event: CustomEvent<any>) => void;
        "onSizeChanged"?: (event: CustomEvent<any>) => void;
        "page"?: number;
        "pageSize"?: number;
        "sizeOptions"?: number[];
    }
    interface IntrinsicElements {
        "wc-goc-paginator": WcGocPaginator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-goc-paginator": LocalJSX.WcGocPaginator & JSXBase.HTMLAttributes<HTMLWcGocPaginatorElement>;
        }
    }
}
